import Navigation from './components/Navigation'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-[#222831] to-[#00ADB5] min-h-screen max-w-[1440px] m-auto flex flex-col justify-center items-center">
        <Navigation />
        {children}</body>
    </html>
  )
}
